name: passwd
description: A beautiful and secure password manager.
version: 1.0.0+1
author: Akshit Garg

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^1.1.2
  archive: ^2.0.13
  async_redux: ^4.0.2
  barcode_scan: ^3.0.1
  base_x: ^1.0.1
  cached_network_image: ^2.3.3
  crayola: ^1.0.0+1
  crypto: ^2.1.5
  cryptography: ^1.4.1
  dart_otp: ^1.3.0
  dio: ^3.0.10
  encrypt: ^4.1.0
  ez_localization: ^0.3.0+1
  flutter_icons: ^1.1.0
  flutter_otp_text_field: ^0.0.1+1
  flutter_secure_storage: ^3.3.4
  functional_data: ^0.3.0
  get_it: ^5.0.1
  google_fonts: ^1.1.1
  injectable: ^1.0.5
  local_auth: ^0.6.3+3
  msgpack_dart: ^0.0.7
  path: ^1.7.0
  path_provider: ^1.6.21
  percent_indicator: ^2.1.7
  provider: ^4.3.2+2
  provider_for_redux: ^1.1.3
  responsive_builder: ^0.3.0
  shared_preferences: ^0.5.12+2
  supercharged: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.2
  flutter_launcher_icons: ^0.8.1
  functional_data_generator: ^0.3.4
  injectable_generator: ^1.0.5
  pedantic: ^1.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/languages/

flutter_icons:
  android: true
  ios: true
  image_path_ios: assets/icons/ios.png
  image_path_android: assets/icons/android.png
  image_path: assets/icons/ios.png
  adaptive_icon_background: assets/icons/adaptive_bg.png
  adaptive_icon_foreground: assets/icons/adaptive_fg.png
